name: Build and Release (Multi-Platform)

on:
  push:
    branches: [ main, master ]
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform:
          - { os: linux,   arch: amd64, ext: '',    name: 'linux-amd64' }
          - { os: windows, arch: amd64, ext: '.exe', name: 'windows-amd64' }

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.21'

      - name: Build for ${{ matrix.platform.name }}
        run: |
          mkdir -p ./bin
          GOOS=${{ matrix.platform.os }} GOARCH=${{ matrix.platform.arch }} go build -o ./bin/myapp${{ matrix.platform.ext }} ./run.go
          echo "✅ Built: ./bin/myapp${{ matrix.platform.ext }}"

      - name: Package for ${{ matrix.platform.name }}
        run: |
          mkdir -p ./release/${{ matrix.platform.name }}
          cp ./bin/myapp${{ matrix.platform.ext }} ./release/${{ matrix.platform.name }}/myapp${{ matrix.platform.ext }}
          cd ./release/${{ matrix.platform.name }} && zip -r ../../myapp-${{ matrix.platform.name }}.zip myapp${{ matrix.platform.ext }}

